name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering
    inputs:
      publish_to_pypi:
        description: 'Publish to PyPI (not just test)'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  test:
    name: Test Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync --all-extras
    
    - name: Run tests
      run: |
        uv run python test_server.py
        uv run python test_auth.py
        uv run python test_startup.py
    
    - name: Test package build
      run: uv build
    
    - name: Test package installation
      shell: bash
      run: |
        WHEEL_FILE=$(ls dist/*.whl)
        uv pip install "$WHEEL_FILE"
        uv pip show league-analysis-mcp-server
        echo "Testing package import..."
        uv run python -c "import league_analysis_mcp_server; print('Package imported successfully')"

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for version tags
    
    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install build dependencies
      run: uv sync
    
    - name: Build package
      run: uv build
    
    - name: Verify build
      shell: bash
      run: |
        ls -la dist/
        WHEEL_FILE=$(ls dist/*.whl)
        uv pip install "$WHEEL_FILE"
        uv pip show league-analysis-mcp-server
        echo "Testing package import..."
        uv run python -c "import league_analysis_mcp_server; print('Built package works!')"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/

  publish-test:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        path: dist/
    
    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Publish to TestPyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: uv publish --publish-url https://test.pypi.org/legacy/
    
    - name: Test TestPyPI installation
      run: |
        sleep 60  # Wait for package to be available
        # Test that the package can be run via uvx (the recommended method)
        timeout 10 uvx --from league-analysis-mcp-server@latest --index-url https://test.pypi.org/simple/ --with-requirements pypi league-analysis-mcp-server --help || true
        # Also test basic import
        uv run --with league-analysis-mcp-server --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ python -c "import league_analysis_mcp_server; print('TestPyPI package works!')"

  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build, publish-test]
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_pypi == 'true')
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        path: dist/
    
    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Publish to PyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: uv publish
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this release
          
          Install with: `uvx league-analysis-mcp-server` or `pip install league-analysis-mcp-server`
          
          See the [changelog](CHANGELOG.md) for details.
        draft: false
        prerelease: false